### ISSUE TITLE
infinitybotlist.com not working

### ISSUE THREAD

**Issue by L0SER8228** [botblock/BLAPI#80] opened 2021-05-23 01:31 UTC
I checked everything correctly, for others sites it's working fine. But for infinitybotlist.com, it's not posting stats

**Comment by T0TProduction** [comment] 2021-05-23 11:21
is it throwing any errors? 
could you enable extended logging and see what it logs there?
could be that just their API is down, we had such occurrences in the past with other lists.

**Comment by L0SER8228** [comment] 2021-05-23 12:47
Okk, let me enable extended logging and check

**Comment by L0SER8228** [comment] 2021-05-24 11:24
![IMG_20210524_164937](https://user-images.githubusercontent.com/65214509/119340741-8c5b6d00-bcb0-11eb-9b6d-459f8e1f922b.jpg)
I reported them the bug, they said they fixed it. So can you check the API now

**Comment by T0TProduction** [comment] 2021-05-24 12:15
Does it work for you now? If they changed their API to acommodate the auth header, blapi wouldnt need any changes, right?


@MattIPv4 heads up that apparently this API was not correctly listed, as their endpoints didnt work with BotBlocks auth headers. Fixed now (on their side), but still something to potentially look out for when new lists are added from now on

**Comment by L0SER8228** [comment] 2021-05-24 12:21
I restart my bot more than 1 hour ago, and set the blapi to post stats every 30 minutes. But they stats didn't appear on infinitybotlist.com yet

**Comment by T0TProduction** [comment] 2021-05-24 12:23
> is it throwing any errors?
> could you enable extended logging and see what it logs there?
> could be that just their API is down, we had such occurrences in the past with other lists.

try this again? what did it even log the first time? if you don't tell me, I can't really know if there is any issue with BLAPI

**Comment by L0SER8228** [comment] 2021-05-24 12:27
I didn't log anything yet after restart, I've to wait sometimes to tell you the log

**Comment by L0SER8228** [comment] 2021-05-24 13:05
[INFO][BLAPI:  POSTED TO HTTPS://TOP.GG/API/BOTS/734590862620753970/STATS][24-05-2021, 12:48:54 pm]: undefined
2021-05-24T12:48:54.435701+00:00 app[worker.1]: [INFO][BLAPI:  STATUSCODE: 200][24-05-2021, 12:48:54 pm]: undefined
2021-05-24T12:48:54.435760+00:00 app[worker.1]: [INFO][BLAPI:  HEADERS: [OBJECT OBJECT]][24-05-2021, 12:48:54 pm]: undefined
2021-05-24T12:48:54.435823+00:00 app[worker.1]: [INFO][BLAPI:  DATA: {}][24-05-2021, 12:48:54 pm]: undefined

**Comment by T0TProduction** [comment] 2021-05-24 13:22
> [INFO][BLAPI: POSTED TO HTTPS://TOP.GG/API/BOTS/734590862620753970/STATS][24-05-2021, 12:48:54 pm]: undefined
> 2021-05-24T12:48:54.435701+00:00 app[worker.1]: [INFO][BLAPI: STATUSCODE: 200][24-05-2021, 12:48:54 pm]: undefined
> 2021-05-24T12:48:54.435760+00:00 app[worker.1]: [INFO][BLAPI: HEADERS: [OBJECT OBJECT]][24-05-2021, 12:48:54 pm]: undefined
> 2021-05-24T12:48:54.435823+00:00 app[worker.1]: [INFO][BLAPI: DATA: {}][24-05-2021, 12:48:54 pm]: undefined

to me this looks like blapi only tried posting to top.gg, which was successful with code 200
are there any other logs concerning posting stats?

**Comment by L0SER8228** [comment] 2021-05-24 13:24
Noo i didn't saw previous also
It shows only top.gg success log, though it post stats to almost every sites

**Comment by L0SER8228** [comment] 2021-05-24 13:24
Wonderbotlist is also not working

**Comment by T0TProduction** [comment] 2021-05-24 13:31
what is your config
meaning what timeout are you using (30min, as you mentioned earlier?)
and are you using BotBlock, or turned it off?

**Comment by L0SER8228** [comment] 2021-05-24 13:37
I'm always using the api , the timeout is 30 minutes

**Comment by T0TProduction** [comment] 2021-05-24 13:40
i will see if the logging needs changes and come back to you - even if there is no bug with posting, we will at least find that out when the logging gives us all the info we need.

**Comment by L0SER8228** [comment] 2021-05-24 13:42
"blapi": "^2.1.0",

**Comment by T0TProduction** [comment] 2021-05-24 13:55
I just looked at the logging code and it should post top.gg extra (because they blacklisted botblock), just like it did for you.

but it should also definitely log that it posted to `https://botblock.org/api/count` and the response it got there.
It definitely did not do that for you?
if so, could you share you apiKeys object? (pls censor the keys beforehand tho)

**Comment by cheesycod** [comment] 2021-05-24 14:00
Top.gg didn’t blacklist botblock as i can post stats fine. They just need a auth header for everything including get bot

**Comment by L0SER8228** [comment] 2021-05-24 14:01
![IMG_20210524_193040](https://user-images.githubusercontent.com/65214509/119358825-a142fb00-bcc6-11eb-905c-99b132e88e9c.jpg)

**Comment by T0TProduction** [comment] 2021-05-24 14:06
> Top.gg didn’t blacklist botblock as i can post stats fine. They just need a auth header for everything including get bot

do you post directly to the botblock API? or are you using BLAPI? if the latter, then yes that's intended behavior, because BLAPI always takes top.gg and manually sends it there, even when the use of botblock is activated

**Comment by cheesycod** [comment] 2021-05-24 14:08
We directly use aiohttp to post to botblock

**Comment by T0TProduction** [comment] 2021-05-24 14:14
> We directly use aiohttp to post to botblock

good to know! I'll investigate this further and streamline the BLAPI code if this is really the case, as for years we had to handle top.gg extra.

nonetheless, this doesn't solve the issue of the logging not including *anything* about posting to the botblock API
tbh I cant really see how it would just not log anything for you @L0SER8228

**Comment by T0TProduction** [comment] 2021-05-24 14:57
@L0SER8228 you're defintely not getting any other logs?
could you try posting directly to botblock and see what that call returns? (https://botblock.org/api/docs#count)

**Comment by L0SER8228** [comment] 2021-05-24 15:00
No i didn't post directly, I'm using blapi only and write the code which is on the readme.

**Comment by L0SER8228** [comment] 2021-05-24 15:03
Some others issue, (different topic)
Some sites is no longer available or not responding ( arcane-center.xyz, botrix.cc, nooder.co

**Comment by T0TProduction** [comment] 2021-05-24 15:04
> No i didn't post directly, I'm using blapi only and write the code which is on the readme.

i didn't ask if you did, I asked you to do so

**Comment by T0TProduction** [comment] 2021-05-24 15:05
> Some others issue, (different topic)
> Some sites is no longer available or not responding ( arcane-center.xyz, botrix.cc, nooder.co

that doesn't concern this lib specifically though, if they are really down, you could/should mark that on botblock.org so that they are marked unavailable there

**Comment by T0TProduction** [comment] 2021-05-24 15:07
@L0SER8228 but the most important thing rn is that you just post ALL logs here. that might make it very obvious what is going wrong, and we don't even need to manually test botblock etc.

**Comment by L0SER8228** [comment] 2021-05-24 15:10
> Wonderbotlist is also not working

**Comment by L0SER8228** [comment] 2021-05-24 15:11
So what to do now

**Comment by cheesycod** [comment] 2021-05-24 15:11
> So what to do now

Please post directly to the botblock API, post all logs including non blapi ones here please

**Comment by T0TProduction** [comment] 2021-05-24 15:12
the logs are more important, you can try posting directly to botblock API afterwards, but I still think the logs will already help enough

**Comment by L0SER8228** [comment] 2021-05-24 15:17
2021-05-24T14:48:52.843538+00:00 app[worker.1]:             498,
2021-05-24T14:48:52.843538+00:00 app[worker.1]:             "{\"MESSAGE\":\"LA CLÃ‰ API EST INVALIDE\",\"STATUS\":498}",
2021-05-24T14:48:52.843539+00:00 app[worker.1]:             "{\"SERVEURS\":236}"
2021-05-24T14:48:52.843539+00:00 app[worker.1]:         ]
2021-05-24T14:48:52.843539+00:00 app[worker.1]:     }
2021-05-24T14:48:52.843539+00:00 app[worker.1]: }][24-05-2021, 14:48:52 pm]: undefined
2021-05-24T14:48:53.489482+00:00 app[worker.1]: [INFO][BLAPI:  POSTED TO HTTPS://TOP.GG/API/BOTS/734590862620753970/STATS][24-05-2021, 14:48:53 pm]: undefined
2021-05-24T14:48:53.489529+00:00 app[worker.1]: [INFO][BLAPI:  STATUSCODE: 200][24-05-2021, 14:48:53 pm]: undefined
2021-05-24T14:48:53.489586+00:00 app[worker.1]: [INFO][BLAPI:  HEADERS: [OBJECT OBJECT]][24-05-2021, 14:48:53 pm]: undefined
2021-05-24T14:48:53.489646+00:00 app[worker.1]: [INFO][BLAPI:  DATA: {}][24-05-2021, 14:48:53 pm]: undefined

**Comment by L0SER8228** [comment] 2021-05-24 15:17
Only this much for now

**Comment by cheesycod** [comment] 2021-05-24 15:18
Are you sure that’s the full logs AND stats to other lists are being sent

**Comment by L0SER8228** [comment] 2021-05-24 15:19
> Only this much for now

**Comment by L0SER8228** [comment] 2021-05-24 15:21
2021-05-24T14:48:52.843538+00:00 app[worker.1]:             498,
2021-05-24T14:48:52.843538+00:00 app[worker.1]:             "{\"MESSAGE\":\"LA CLÃ‰ API EST INVALIDE\",\"STATUS\":498}",
2021-05-24T14:48:52.843539+00:00 app[worker.1]:             "{\"SERVEURS\":236}"
2021-05-24T14:48:52.843539+00:00 app[worker.1]:         ]
2021-05-24T14:48:52.843539+00:00 app[worker.1]:     }
2021-05-24T14:48:52.843539+00:00 app[worker.1]: }][24-05-2021, 14:48:52 pm]: undefined
2021-05-24T14:48:53.489482+00:00 app[worker.1]: [INFO][BLAPI:  POSTED TO HTTPS://TOP.GG/API/BOTS/734590862620753970/STATS][24-05-2021, 14:48:53 pm]: undefined
2021-05-24T14:48:53.489529+00:00 app[worker.1]: [INFO][BLAPI:  STATUSCODE: 200][24-05-2021, 14:48:53 pm]: undefined
2021-05-24T14:48:53.489586+00:00 app[worker.1]: [INFO][BLAPI:  HEADERS: [OBJECT OBJECT]][24-05-2021, 14:48:53 pm]: undefined
2021-05-24T14:48:53.489646+00:00 app[worker.1]: [INFO][BLAPI:  DATA: {}][24-05-2021, 14:48:53 pm]: undefined
2021-05-24T15:16:30.230608+00:00 app[worker.1]: DiscordAPIError: Unknown Message
2021-05-24T15:16:30.230616+00:00 app[worker.1]:     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
2021-05-24T15:16:30.230617+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)
2021-05-24T15:16:30.230618+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-05-24T15:16:30.230618+00:00 app[worker.1]:     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
2021-05-24T15:16:30.230619+00:00 app[worker.1]:     at async MessageManager.delete (/app/node_modules/discord.js/src/managers/MessageManager.js:126:5) {
2021-05-24T15:16:30.230620+00:00 app[worker.1]:   method: 'delete',
2021-05-24T15:16:30.230620+00:00 app[worker.1]:   path: '/channels/622565708622069805/messages/846368313654640690',
2021-05-24T15:16:30.230621+00:00 app[worker.1]:   code: 10008,
2021-05-24T15:16:30.230622+00:00 app[worker.1]:   httpStatus: 404
2021-05-24T15:16:30.230622+00:00 app[worker.1]: }
2021-05-24T15:16:30.244972+00:00 app[worker.1]: DiscordAPIError: Unknown Message
2021-05-24T15:16:30.244973+00:00 app[worker.1]:     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
2021-05-24T15:16:30.244973+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)
2021-05-24T15:16:30.244974+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-05-24T15:16:30.244974+00:00 app[worker.1]:     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
2021-05-24T15:16:30.244975+00:00 app[worker.1]:   method: 'delete',
2021-05-24T15:16:30.244975+00:00 app[worker.1]:   path: '/channels/622565708622069805/messages/846368313654640690/reactions',
2021-05-24T15:16:30.244976+00:00 app[worker.1]:   code: 10008,
2021-05-24T15:16:30.244976+00:00 app[worker.1]:   httpStatus: 404
2021-05-24T15:16:30.244976+00:00 app[worker.1]: }
2021-05-24T15:18:52.654785+00:00 app[worker.1]: [INFO][BLAPI:  POSTED TO HTTPS://BOTBLOCK.ORG/API/COUNT][24-05-2021, 15:18:52 pm]: undefined
2021-05-24T15:18:52.655042+00:00 app[worker.1]: [INFO][BLAPI:  STATUSCODE: 200][24-05-2021, 15:18:52 pm]: undefined
2021-05-24T15:18:52.655254+00:00 app[worker.1]: [INFO][BLAPI:  HEADERS: [OBJECT OBJECT]][24-05-2021, 15:18:52 pm]: undefined
2021-05-24T15:18:52.655459+00:00 app[worker.1]: [INFO][BLAPI:  DATA: {
2021-05-24T15:18:52.655459+00:00 app[worker.1]:     "SUCCESS": {
2021-05-24T15:18:52.655460+00:00 app[worker.1]:         "BLADEBOTLIST.XYZ": [
2021-05-24T15:18:52.655460+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655461+00:00 app[worker.1]:             "{\"OK\":\"SUCCESSFULLY POSTED 236 SERVERS FOR THE BOT DEEJAY#2424 AND (IF DEFINED) SHARDS!\",\"ERRCODE\":200}",
2021-05-24T15:18:52.655462+00:00 app[worker.1]:             "{\"SERVER_COUNT\":236}"
2021-05-24T15:18:52.655463+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655463+00:00 app[worker.1]:         "BLIST.XYZ": [
2021-05-24T15:18:52.655464+00:00 app[worker.1]:             204,
2021-05-24T15:18:52.655464+00:00 app[worker.1]:             "\"\"",
2021-05-24T15:18:52.655464+00:00 app[worker.1]:             "{\"SERVER_COUNT\":236}"
2021-05-24T15:18:52.655464+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655465+00:00 app[worker.1]:         "BOTSFORDISCORD.COM": [
2021-05-24T15:18:52.655465+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655466+00:00 app[worker.1]:             "{\"MESSAGE\":\"SERVER COUNT SUCCESSFULLY UPDATED.\"}",
2021-05-24T15:18:52.655466+00:00 app[worker.1]:             "{\"SERVER_COUNT\":236}"
2021-05-24T15:18:52.655467+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655467+00:00 app[worker.1]:         "BOTS.DISCORDLABS.ORG": [
2021-05-24T15:18:52.655467+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655468+00:00 app[worker.1]:             "{\"ERROR\":\"FALSE\"}",
2021-05-24T15:18:52.655468+00:00 app[worker.1]:             "{\"SERVER_COUNT\":236}"
2021-05-24T15:18:52.655468+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655469+00:00 app[worker.1]:         "DISCORD.BOATS": [
2021-05-24T15:18:52.655469+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655470+00:00 app[worker.1]:             "{\"ERROR\":FALSE,\"MESSAGE\":\"SERVER COUNT UPDATED.\"}",
2021-05-24T15:18:52.655470+00:00 app[worker.1]:             "{\"SERVER_COUNT\":236}"
2021-05-24T15:18:52.655470+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655471+00:00 app[worker.1]:         "DISCORD.BOTS.GG": [
2021-05-24T15:18:52.655471+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655472+00:00 app[worker.1]:             "{\"SHARDCOUNT\":1,\"GUILDCOUNT\":236}",
2021-05-24T15:18:52.655472+00:00 app[worker.1]:             "{\"GUILDCOUNT\":236}"
2021-05-24T15:18:52.655472+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655473+00:00 app[worker.1]:         "DISCORDBOTLIST.COM": [
2021-05-24T15:18:52.655473+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655473+00:00 app[worker.1]:             "{\"SUCCESS\":TRUE}",
2021-05-24T15:18:52.655474+00:00 app[worker.1]:             "{\"GUILDS\":236}"
2021-05-24T15:18:52.655474+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655474+00:00 app[worker.1]:         "DISCORDLIST.SPACE": [
2021-05-24T15:18:52.655475+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655475+00:00 app[worker.1]:             "{\"CODE\":200,\"MESSAGE\":\"SUCCESSFULLY UPDATED SERVER COUNT\"}",
2021-05-24T15:18:52.655476+00:00 app[worker.1]:             "{\"SERVER_COUNT\":236}"
2021-05-24T15:18:52.655476+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655476+00:00 app[worker.1]:         "DISCORDEXTREMELIST.XYZ": [
2021-05-24T15:18:52.655476+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655477+00:00 app[worker.1]:             "{\"ERROR\":FALSE,\"STATUS\":200,\"UPDATED\":{\"GUILDCOUNT\":236,\"SHARDCOUNT\":0}}",
2021-05-24T15:18:52.655478+00:00 app[worker.1]:             "{\"GUILDCOUNT\":236}"
2021-05-24T15:18:52.655478+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655478+00:00 app[worker.1]:         "DISFORGE.COM": [
2021-05-24T15:18:52.655478+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655479+00:00 app[worker.1]:             "{\"STATUS\":\"ERROR\",\"MESSAGE\":\"YOU CAN UPDATE YOUR BOTS STATS ONCE PER HOUR\"}",
2021-05-24T15:18:52.655479+00:00 app[worker.1]:             "{\"SERVERS\":236}"
2021-05-24T15:18:52.655479+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655480+00:00 app[worker.1]:         "FATESLIST.XYZ": [
2021-05-24T15:18:52.655480+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655480+00:00 app[worker.1]:             "{\"DONE\":TRUE,\"REASON\":NULL,\"CODE\":1000}",
2021-05-24T15:18:52.655481+00:00 app[worker.1]:             "{\"GUILD_COUNT\":236}"
2021-05-24T15:18:52.655481+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655481+00:00 app[worker.1]:         "PARADISEBOTS.NET": [
2021-05-24T15:18:52.655482+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655482+00:00 app[worker.1]:             "{\"PARADISEAPI\":\" YOUR STATS HAVE BEEN POSTED.\",\"ERROR\":FALSE,\"STATUS\":\"200\"}",
2021-05-24T15:18:52.655482+00:00 app[worker.1]:             "{\"SERVER_COUNT\":236}"
2021-05-24T15:18:52.655482+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655483+00:00 app[worker.1]:         "SPACE-BOT-LIST.XYZ": [
2021-05-24T15:18:52.655483+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655483+00:00 app[worker.1]:             "{\"SERVERS\":236}",
2021-05-24T15:18:52.655483+00:00 app[worker.1]:             "{\"GUILDS\":236}"
2021-05-24T15:18:52.655484+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655484+00:00 app[worker.1]:         "TOP.GG": [
2021-05-24T15:18:52.655484+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655484+00:00 app[worker.1]:             "{}",
2021-05-24T15:18:52.655485+00:00 app[worker.1]:             "{\"SERVER_COUNT\":236}"
2021-05-24T15:18:52.655485+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655485+00:00 app[worker.1]:         "VOIDBOTS.NET": [
2021-05-24T15:18:52.655485+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655486+00:00 app[worker.1]:             "{\"MESSAGE\":\"SERVERCOUNT UPDATED!\"}",
2021-05-24T15:18:52.655486+00:00 app[worker.1]:             "{\"SERVER_COUNT\":236}"
2021-05-24T15:18:52.655486+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655486+00:00 app[worker.1]:         "YABL.XYZ": [
2021-05-24T15:18:52.655486+00:00 app[worker.1]:             200,
2021-05-24T15:18:52.655496+00:00 app[worker.1]:             "{\"ID\":\"734590862620753970\",\"PREFIX\":\">\",\"HELP\":\">HELP\",\"DESC\":\"DISOCRD MUSIC BOT. REACTION CONTROLLED. DJ MODE. 25+ AUDIO FILTERS. YOUTUBE, SOUNDCLOUD , SPOTIFY & 700+ MORE SITES SUPPORTED.\",\"BODY\":\"__**DEEJAY - MUSIC FOR EVERY MOOD**__\\N\\N\\NDISOCRD MUSIC BOT. REACTION CONTROLLED. DJ MODE. 25+ AUDIO FILTERS. YOUTUBE, SOUNDCLOUD , SPOTIFY &#X26; 700+ MORE SITES SUPPORTED.\\N\\N\\N**SUPPORTED STREAMING PLATFORMS**\\NYOUTUBE, SOUNDCLOUD, SPOTIFY, VIMEO, REVERBNATION, FACEBOOK, DISCORD ATTACHMENT LINKS ALSO &#X26; [700+ MORE](HTTPS://YTDL-ORG.GITHUB.IO/YOUTUBE-DL/SUPPORTEDSITES.HTML) SITES LINKS SUPPORTED\\N\\N\\N\\N**REACTION CONTROLS**\\N\\N1)&#X23ED;&#XFE0F; SKIP TO THE NEXT SONG.\\N\\N2)&#X23EE;&#XFE0F; BACK TO THE PREVIOUS SONG.\\N\\N3)&#X23EF;&#XFE0F; PAUSE/RESUME THE SONG.\\N\\N4)&#X1F509; VOLUME DOWN 10 %\\N\\N5)&#X1F50A; VOLUME UP 10 %\\N\\N6)&#X23EA; REWIND 10 SECONDS\\N\\N7)&#X23E9; FORWARD 10 SECONDS\\N\\N8)&#X1F501; SWITCH BETWEEN THE LOOP MODES.(SONG, QUEUE, OFF)\\N\\N9)&#X21A9;&#XFE0F; RESTART THE SONG\\N\\N10)&#X1F3B6; ON/OFF AUTOPLAY\\N\\N11)&#X1F500; SHUFFLE THE QUEUE.\\N\\N12)&#X23F9; STOP THEN LEAVE THE VOICE CHANNEL\\N\\N\\N\\N__**MUSIC COMMANDS**__\\N\\NADDRELATED, AUTOPLAY, BACKWARD, BUMP, CLEARQUEUE, FILTER, FORWARD, JOIN, JUMP, LYRICS, MOVE, NOWPLAYING, PAUSE, PLAY, PLAYSKIP, PREVIOUS, QUEUE, REMOVE, REPEAT, REPLAY, RESUME, SEARCH, SEEK, SHUFFLE, SKIP, SONGINFO, STOP, SWAP, VOLUME\\N\\N\\N\\N__**AUDIO FILTERS**__\\N\\N3D, BASSBOOST, ECHO, FLANGER, GATE, HAAS, KARAOKE, NIGHTCORE, REVERSE, VAPORWAVE, MCOMPAND, PHASER, TREMOLO, SURROUND, EARWAX, 8D, CHORUS, CHORUS2D, CHORUS3D, CLEAR, COMPRESSOR, CURSED, DESILENCER, EARRAPE, EXPANDER, FADEIN, MONO, MSTLR, MSTRR, NORMALIZER, PULSATOR, PUREBASS, RICKROLL, SOFTLIMITER, SUBBOOST, VIBRATO, TREBLE, DOUBLE, SPEED, NORMAL, HALF, OFF\\N\\N\\N\\N**UTILITY COMMAD**\\N\\NHELP, BOTINFO, BOTINVITE, BUGREPORT,  PING, UPTIME, SUPPORT, UPVOTE, FEEDBACK\\N\\N\\N\\N**__ADMIN COMMANDS (SERVER SETTINGS)__**\\N\\NBAN, PREFIX, UNBAN, DISABLE, ENABLE, REACTIONCONTROL\",\"WEBSITE\":\"HTTPS://DEEJAYBOT.TK\",\"SUPPORT\":\"HTTPS://DISCORD.GG/4YPXU7BMF9\",\"GIT\":NULL,\"LIBRARY\":\"DISCORD.JS\",\"MODNOTE\":NULL,\"VERIFIED\":FALSE,\"OWNERS\":{\"668157292927254587\":\"L0SER#8228\"},\"USERNAME\":\"DEEJAY\",\"AVATAR\":\"884703E3103AC0EE4F81116057F07507\",\"GUILDCOUNT\":236}",
2021-05-24T15:18:52.655497+00:00 app[worker.1]:             "{\"GUILDCOUNT\":236}"
2021-05-24T15:18:52.655497+00:00 app[worker.1]:         ]
2021-05-24T15:18:52.655497+00:00 app[worker.1]:     },
2021-05-24T15:18:52.655497+00:00 app[worker.1]:     "FAILURE": {
2021-05-24T15:18:52.655498+00:00 app[worker.1]:         "BOTS.ONDISCORD.XYZ": [
2021-05-24T15:18:52.655498+00:00 app[worker.1]:             404,
2021-05-24T15:18:52.655498+00:00 app[worker.1]:             "{\"MESSAGE\":\"BOT NOT FOUND OR NOT APPROVED\"}",
2021-05-24T15:18:52.655499+00:00 app[worker.1]:             "{\"GUILDCOUNT\":236}"
2021-05-24T15:18:52.655499+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655499+00:00 app[worker.1]:         "INFINITYBOTLIST.COM": [
2021-05-24T15:18:52.655500+00:00 app[worker.1]:             404,
2021-05-24T15:18:52.655500+00:00 app[worker.1]:             "{\"MESSAGE\":\"AUTHORIZATION TOKEN NOT FOUND, PLEASE PROVIDE A VALID API TOKEN!\",\"ERROR\":TRUE,\"STATUS\":404}",
2021-05-24T15:18:52.655500+00:00 app[worker.1]:             "{\"SERVERS\":236}"
2021-05-24T15:18:52.655501+00:00 app[worker.1]:         ],
2021-05-24T15:18:52.655501+00:00 app[worker.1]:         "WONDERBOTLIST.COM": [
2021-05-24T15:18:52.655501+00:00 app[worker.1]:             498,
2021-05-24T15:18:52.655502+00:00 app[worker.1]:             "{\"MESSAGE\":\"LA CLÃ‰ API EST INVALIDE\",\"STATUS\":498}",
2021-05-24T15:18:52.655502+00:00 app[worker.1]:             "{\"SERVEURS\":236}"
2021-05-24T15:18:52.655502+00:00 app[worker.1]:         ]
2021-05-24T15:18:52.655502+00:00 app[worker.1]:     }
2021-05-24T15:18:52.655503+00:00 app[worker.1]: }][24-05-2021, 15:18:52 pm]: undefined
2021-05-24T15:18:53.236480+00:00 app[worker.1]: [INFO][BLAPI:  POSTED TO HTTPS://TOP.GG/API/BOTS/734590862620753970/STATS][24-05-2021, 15:18:53 pm]: undefined
2021-05-24T15:18:53.236547+00:00 app[worker.1]: [INFO][BLAPI:  STATUSCODE: 200][24-05-2021, 15:18:53 pm]: undefined
2021-05-24T15:18:53.236604+00:00 app[worker.1]: [INFO][BLAPI:  HEADERS: [OBJECT OBJECT]][24-05-2021, 15:18:53 pm]: undefined
2021-05-24T15:18:53.236669+00:00 app[worker.1]: [INFO][BLAPI:  DATA: {}][24-05-2021, 15:18:53 pm]: undefined

**Comment by T0TProduction** [comment] 2021-05-24 15:21
since the top most log is showing an error code of 498 I for a fact know there are more logs above it.
but even that already tells us the issue is that your token is expired/invalid. so that's your issue.

**Comment by T0TProduction** [comment] 2021-05-24 15:22
some lists are giving you a 498, which means your token is invalid.
also, infinity e.g. tells you your don't even have the bot listed (404)
if you had shown this information from the start it would have been very clear what is going wrong.

this is most definitely not an issue with BLAPI, but your tokens

**Comment by MattIPv4** [comment] 2021-05-24 15:23
> @L0SER8228 Does it work for you now? If they changed their API to acommodate the auth header, blapi wouldnt need any changes, right?
> 
> @MattIPv4 heads up that apparently this API was not correctly listed, as their endpoints didnt work with BotBlocks auth headers. Fixed now (on their side), but still something to potentially look out for when new lists are added from now on

LULW -- case sensitive header detection is definitely a new one for me.

**Comment by cheesycod** [comment] 2021-05-24 15:24
> > @MattIPv4 heads up that apparently this API was not correctly listed, as their endpoints didnt work with BotBlocks auth headers. Fixed now (on their side), but still something to potentially look out for when new lists are added from now on
> 
> LULW -- case sensitive header detection is definitely a new one for me.

Aren’t headers were supposed to be case insensitive

**Comment by L0SER8228** [comment] 2021-05-24 15:26
I can ensure my bot has been approved, I'll check the tokens,. If the problem still exists, I'll tell you

**Comment by T0TProduction** [comment] 2021-05-24 15:29
yeah, taking a closer look the 404 seems to also say invalid token (which is not that that error code stands for.).
closing this, if the issue persists we can reopen

**Closed by T0TProduction** 2021-05-24 15:29 UTC
Labels: investigating

**Comment by TheRealToxicDev** [comment] 2021-05-24 16:25
Header and Case Sensitivity issues have been fixed for Infinity sorry about that 😳😬

**Comment by cheesycod** [comment] 2021-05-25 03:44
Have you tried directly using their API and making sure it isn’t a botblock problem

**Comment by TheRealToxicDev** [comment] 2021-05-25 04:13
@cheesycod Well on our end the uhh trigger for that error is !auth which indicates there was no auto token provided or something about the actual header request is wrong. 

Posting stats via our NPM Module or Node-Fetch, AIOHTTP or anything of the sort should be successful as it works for me and all others who use it. I personally have never attempted to use the Infinity API via this module but I can definitely do that and see if I can recreate 🤔

**Comment by T0TProduction** [comment] 2021-05-25 07:14
@L0SER8228 
Since it obviously updates *some* lists, the part that this library does cannot be the issue.
Either BotBlock has an outdated documentation of those APIs and/or doesnt post in the correct format, or you are still doing something wrong with the tokens.

One thing you could try is turn *off* the use of BotBlock in BLAPI. It will then post to all lists individually, which might help you find where the problem stems from.
